export const ErrorCodes: any = {
  UserNotMoniest: "User is not moniest",
  UserNotFoundByID: "User not found with this user ID",

  Account_Authorization_NotProvidedHeader: "Authorization Header is not provided",
  Account_Authorization_InvalidHeader: "Authorization Header is invalid",
  Account_Authorization_UnsupportedType: "Authorization Type is not supported",
  Account_Authorization_InvalidToken: "Authorization Token is invalid",

  Account_Login_InvalidBody: "Login request body is invalid",
  Account_Login_InvalidEmail: "Email is invalid",
  Account_Login_InvalidUsername: "Username is invalid",
  Account_Login_NotFoundEmail: "Email is not in the system",
  Account_Login_NotFoundUsername: "Username is not in the system",
  Account_Login_ServerErrorEmail: "Server error on login with email",
  Account_Login_ServerErrorUsername: "Server error on login with username",
  Account_Login_WrongPassword: "Wrong password",
  Account_Login_ServerErrorToken: "Server error on token operation",

  Account_Register_InvalidBody: "Register request body is invalid",
  Account_Register_InvalidEmail: "Email is invalid",
  Account_Register_InvalidUsername: "Username is invalid",
  Account_Register_InvalidPassword: "Password is invalid",
  Account_Register_ServerErrorCheckEmail: "Server error on checking email",
  Account_Register_ServerErrorCheckUsername: "Server error on checking username",
  Account_Register_RegisteredEmail: "Email is already registered",
  Account_Register_RegisteredUsername: "Username is already registered",
  Account_Register_ServerErrorPassword: "Server error on password operation",
  Account_Register_ServerErrorCreateUser: "Server error on creating user",

  Account_GetUser_NotFound: "User not found",
  Account_GetUser_ServerError: "Server error on getting user",

  Account_CheckUsername_InvalidUsername: "Username is invalid",
  Account_CheckUsername_ServerErrorCheckUsername: "Server error on checking username",

  Account_ChangePassword_InvalidBody: "Change password request body is invalid",
  Account_ChangePassword_InvalidOldPassword: "Old password is invalid",
  Account_ChangePassword_InvalidNewPassword: "New password is invalid",
  Account_ChangePassword_InvalidEmail: "Email is invalid",
  Account_ChangePassword_NotFoundEmail: "Email is not in the system",
  Account_ChangePassword_ServerErrorCheckPassword: "Server error on checking password",
  Account_ChangePassword_ServerErrorCheckEmail: "Server error on checking email",
  Account_ChangePassword_WrongPassword: "Wrong old Password",
  Account_ChangePassword_ServerErrorPassword: "Server error on password operation",
  Account_ChangePassword_ServerErrorUpdatePassword: "Server error on updating password",
  Account_ChangePassword_ServerErrorCreateToken: "Server error on creating token",
  Account_ChangePassowrd_SendEmail: "Server error on sending email",
  Account_ChangePassword_InvalidToken: "Password Reset Token is invalid",
  Account_ChangePassword_NotFoundToken: "Password Reset Token is not in the system",
  Account_ChangePassword_ServerErrorGetToken: "Server error on getting Password Reset Token from system",
  Account_ChangePassword_ExpiredToken: "Password Reset Token is expired",
  Account_ChangePassword_ServerErrorDeleteToken: "Server error on deleting Password Reset Token",

  Account_EmailVerification_ServerErrorGetUser: "Server error on getting user",
  Account_EmailVerification_AlreadyVerified: "The email is already verified",
  Account_EmailVerification_ServerErrorCreateToken: "Server error on creating token",
  Account_EmailVerification_SendEmail: "Server error on sending email",

  Moniest_CreateMoniest_InvalidBody: "Create moniest request body is invalid",
  Moniest_CreateMoniest_ServerErrorUserIsMoniest: "Server error on user is moniest check",
  Moniest_CreateMoniest_UserIsAlreadyMoniest: "This user is already a moniest",
  Moniest_CreateMoniest_InvalidBio: "Bio is invalid",
  Moniest_CreateMoniest_InvalidDescription: "Description is invalid",
  Moniest_CreateMoniest_ServerErrorCreateMoniest: "Server error on create moniest",
  Moniest_CreateMoniest_UnverifiedEmail: "Email is not verified yet",

  Moniest_GetMoniest_NoMoniest: "Not any moniest exist",
  Moniest_GetMoniest_ServerErrorGetMoniest: "Server error on getting moniest",

  Moniest_CreateSubscriptionInfo_InvalidFee: "Fee is invalid",
  Moniest_CreateSubscriptionInfo_InvalidSubscriptionMessage: "Subscription message is invalid",
  Moniest_CreateSubscriptionInfo_ServerErrorOnCreate: "Server error on create subscription info",

  User_GetUser_NotFoundUser: "User not found",
  User_GetUser_ServerErrorGetUser: "Server error on getting user",

  Post_CreatePost_InvalidBody: "Create post request body is invalid",
  Post_CreatePost_InvalidCurrency: "Currency is invalid",
  Post_CreatePost_InvalidDuration: "Duration is invalid",
  Post_CreatePost_InvalidCurrencyPrice: "Currency price is invalid",
  Post_CreatePost_InvalidTargets: "Targets are invalid",
  Post_CreatePost_InvalidStop: "Stop is invalid",
  Post_CreatePost_ServerErrorCreatePost: "Server error on creating post",
  Post_CreatePost_ServerErrorCreateDescription: "Server error on creating description",

  Crypto_GetCurrencies_InvalidParam: "Get Currencies request params is invalid",
  Crypto_GetCurrenciesFromAPI_ServerError: "Server error on getting currencies from API",

}
